name: Govee to MQTT Bridge
image: ghcr.io/wez/govee2mqtt-{arch}
version: "2024.01.24-ea3cd430"
slug: govee2mqtt
description: Control Govee Devices
url: https://github.com/wez/govee2mqtt
arch:
  - amd64
  - aarch64
  - armv7
init: false
startup: services
services:
  - mqtt:need

apparmor: true

webui: http://[HOST]:[PORT:8056]/

# Host network access is required for LAN discovery
host_network: true

options:
  temperature_scale: "C"

schema:
  temperature_scale: "str?"
  govee_email: "str?"
  govee_password: "password?"
  govee_api_key: "password?"
  mqtt_host: "str?"
  mqtt_port: "int?"
  mqtt_username: "str?"
  mqtt_password: "password?"
  debug_level: "str?"
  no_multicast: "bool?"
  broadcast_all: "bool?"
  global_broadcast: "bool?"
  scan: "str?"
